# Generated by Django 4.2.9 on 2024-01-31 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='buun',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_check',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_info',
            field=models.CharField(max_length=100, null=True, verbose_name='Mobile info'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(max_length=100, null=True, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.CharField(max_length=100, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='user',
            name='version',
            field=models.CharField(max_length=100, null=True, verbose_name='Version'),
        ),
        migrations.CreateModel(
            name='MobileInfo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, null=True, verbose_name='Ключ')),
                ('value', models.CharField(max_length=100, null=True, verbose_name='Значение')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
