# Generated by Django 4.2.9 on 2024-01-31 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_buun_user_login_check_user_mobile_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobileinfo2',
            options={'verbose_name': 'Мобильные данные', 'verbose_name_plural': 'Мобильные данные'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='organization',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Ключ позиции'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='specialty',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='mobileinfo2',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='mobileinfo2',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mobileinfo2',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='additional_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.useradditionaldata'),
        ),
        migrations.AlterField(
            model_name='user',
            name='buun',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_check',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mobile info'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_driver_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.userdriverlicense', verbose_name='Водительские права'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_passport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.userpassport', verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='user',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='useradditionaldata',
            name='characters',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отдельные персонажи'),
        ),
        migrations.AlterField(
            model_name='useradditionaldata',
            name='dismissed_order_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер отклоненного заказа'),
        ),
        migrations.AlterField(
            model_name='useradditionaldata',
            name='end_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Время выхода'),
        ),
        migrations.AlterField(
            model_name='useradditionaldata',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Стаж'),
        ),
        migrations.AlterField(
            model_name='useradditionaldata',
            name='order_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Введеный номер заказа'),
        ),
        migrations.AlterField(
            model_name='useradditionaldata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='useradditionaldata',
            name='work_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='userdriverlicense',
            name='category',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='userdriverlicense',
            name='characters',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Персонажи'),
        ),
        migrations.AlterField(
            model_name='userdriverlicense',
            name='date_of_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='userdriverlicense',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания срока'),
        ),
        migrations.AlterField(
            model_name='userdriverlicense',
            name='place_of_issue',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Место выдачи'),
        ),
        migrations.AlterField(
            model_name='userdriverlicense',
            name='testimonial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер свидетельства'),
        ),
        migrations.AlterField(
            model_name='userdriverlicense',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userpassport',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='userpassport',
            name='birth_place',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='userpassport',
            name='citizenship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='userpassport',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата истечения срока'),
        ),
        migrations.AlterField(
            model_name='userpassport',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userpassport',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='userpassport',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userpassport',
            name='passport_seria',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Серия пасспорта'),
        ),
        migrations.AlterField(
            model_name='userpassport',
            name='personal_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Личный номер'),
        ),
        migrations.AlterField(
            model_name='userpassport',
            name='residential_address',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='userpassport',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='userpassport',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='userpassport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Юзер'),
        ),
    ]
