# Generated by Django 4.2.9 on 2024-01-31 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_mobileinfo2_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='additional_data',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_driver_license',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_passport',
        ),
    ]
