# Generated by Django 4.2.9 on 2024-01-31 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QoshimchaMalumotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ozgartirganXodim', models.CharField(blank=True, max_length=100, null=True, verbose_name='ozgartirganXodim')),
                ('qowimchaMalumotlar', models.CharField(blank=True, max_length=100, null=True, verbose_name='qowimchaMalumotlar')),
                ('sana', models.CharField(blank=True, max_length=100, null=True, verbose_name='sana')),
            ],
            options={
                'verbose_name': 'QoshimchaMalumotlar',
                'verbose_name_plural': 'QoshimchaMalumotlar',
            },
        ),
        migrations.CreateModel(
            name='SpidometrKorsatgichi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spidometrKorsatgichi', models.CharField(blank=True, max_length=100, null=True, verbose_name='spidometrKorsatgichi')),
                ('sana', models.CharField(blank=True, max_length=100, null=True, verbose_name='sana')),
                ('ozgartirganXodim', models.CharField(blank=True, max_length=100, null=True, verbose_name='ozgartirganXodim')),
            ],
            options={
                'verbose_name': 'SpidometrKorsatgichi',
                'verbose_name_plural': 'SpidometrKorsatgichi',
            },
        ),
        migrations.CreateModel(
            name='TexnikKorik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ozgartirganXodim', models.CharField(blank=True, max_length=100, null=True, verbose_name='ozgartirganXodim')),
                ('sana', models.CharField(blank=True, max_length=100, null=True, verbose_name='sana')),
                ('xarajatQiymati', models.CharField(blank=True, max_length=100, null=True, verbose_name='xarajatQiymati')),
                ('oxirgiKorikdanOtganSana', models.CharField(blank=True, max_length=100, null=True, verbose_name='oxirgiKorikdanOtganSana')),
            ],
            options={
                'verbose_name': 'TexnikKorik',
                'verbose_name_plural': 'TexnikKorik',
            },
        ),
        migrations.CreateModel(
            name='TSModeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='img')),
                ('gosRaqami', models.CharField(blank=True, max_length=100, null=True, verbose_name='gosRaqami')),
                ('rusumi', models.CharField(blank=True, max_length=100, null=True, verbose_name='rusumi')),
                ('rangi', models.CharField(blank=True, max_length=100, null=True, verbose_name='rangi')),
                ('egasi', models.CharField(blank=True, max_length=100, null=True, verbose_name='egasi')),
                ('manzili', models.CharField(blank=True, max_length=100, null=True, verbose_name='manzili')),
                ('berilganSanasi', models.CharField(blank=True, max_length=100, null=True, verbose_name='berilganSanasi')),
                ('yhxBolimi', models.CharField(blank=True, max_length=100, null=True, verbose_name='yhxBolimi')),
                ('inn', models.CharField(blank=True, max_length=100, null=True, verbose_name='inn')),
                ('ishlabChiqarilganYili', models.CharField(blank=True, max_length=100, null=True, verbose_name='ishlabChiqarilganYili')),
                ('turi', models.CharField(blank=True, max_length=100, null=True, verbose_name='turi')),
                ('kuzovRaqami', models.CharField(blank=True, max_length=100, null=True, verbose_name='kuzovRaqami')),
                ('shassiRaqami', models.CharField(blank=True, max_length=100, null=True, verbose_name='shassiRaqami')),
                ('tolaVazni', models.CharField(blank=True, max_length=100, null=True, verbose_name='tolaVazni')),
                ('yuksizVazni', models.CharField(blank=True, max_length=100, null=True, verbose_name='yuksizVazni')),
                ('dvigatelRaqami', models.CharField(blank=True, max_length=100, null=True, verbose_name='dvigatelRaqami')),
                ('dvigatelQuvvati', models.CharField(blank=True, max_length=100, null=True, verbose_name='dvigatelQuvvati')),
                ('yonilgiTuri', models.CharField(blank=True, max_length=100, null=True, verbose_name='yonilgiTuri')),
                ('otiradiganJoylari', models.CharField(blank=True, max_length=100, null=True, verbose_name='otiradiganJoylari')),
                ('tikTuradiganJoylari', models.CharField(blank=True, max_length=100, null=True, verbose_name='tikTuradiganJoylari')),
                ('alohidaBelgilari', models.CharField(blank=True, max_length=100, null=True, verbose_name='alohidaBelgilari')),
                ('biriktirilganXodim', models.CharField(blank=True, max_length=100, null=True, verbose_name='biriktirilganXodim')),
                ('biriktirilganUMG', models.CharField(blank=True, max_length=100, null=True, verbose_name='biriktirilganUMG')),
                ('sugurtaNomeri', models.CharField(blank=True, max_length=100, null=True, verbose_name='sugurtaNomeri')),
                ('sugurtaTugashKuni', models.CharField(blank=True, max_length=100, null=True, verbose_name='sugurtaTugashKuni')),
                ('sugurtaKompaniyasi', models.CharField(blank=True, max_length=100, null=True, verbose_name='sugurtaKompaniyasi')),
                ('gpsBool', models.BooleanField(blank=True, null=True, verbose_name='gpsBool')),
                ('dutBool', models.BooleanField(blank=True, null=True, verbose_name='dutBool')),
                ('xisobdanChiqarish', models.BooleanField(blank=True, null=True, verbose_name='xisobdanChiqarish')),
                ('yurKotarishKG', models.CharField(blank=True, max_length=100, null=True, verbose_name='yurKotarishKG')),
                ('texnikXolati', models.CharField(blank=True, max_length=100, null=True, verbose_name='texnikXolati')),
            ],
            options={
                'verbose_name': 'TSModeli',
                'verbose_name_plural': 'TSModeli',
            },
        ),
        migrations.CreateModel(
            name='YoqilgiOstatkasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qoldiq', models.CharField(blank=True, max_length=100, null=True, verbose_name='qoldiq')),
                ('sana', models.CharField(blank=True, max_length=100, null=True, verbose_name='sana')),
                ('ozgartirganXodim', models.CharField(blank=True, max_length=100, null=True, verbose_name='ozgartirganXodim')),
                ('narxi', models.CharField(blank=True, max_length=100, null=True, verbose_name='narxi')),
                ('yoqilgiTuri', models.CharField(blank=True, max_length=100, null=True, verbose_name='yoqilgiTuri')),
            ],
            options={
                'verbose_name': 'YoqilgiOstatkasi',
                'verbose_name_plural': 'YoqilgiOstatkasi',
            },
        ),
        migrations.CreateModel(
            name='Zapchast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ozgartirganXodim', models.CharField(blank=True, max_length=100, null=True, verbose_name='ozgartirganXodim')),
                ('sana', models.CharField(blank=True, max_length=100, null=True, verbose_name='sana')),
                ('xarajatQiymati', models.CharField(blank=True, max_length=100, null=True, verbose_name='xarajatQiymati')),
            ],
            options={
                'verbose_name': 'Zapchast',
                'verbose_name_plural': 'Zapchast',
            },
        ),
        migrations.CreateModel(
            name='AlmashtirilganZapchastRoyxati2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='almashtirilganZapchastRoyxati')),
                ('zapchast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.zapchast')),
            ],
            options={
                'verbose_name': 'AlmashtirilganZapchastRoyxati',
                'verbose_name_plural': 'AlmashtirilganZapchastRoyxati',
            },
        ),
        migrations.CreateModel(
            name='AlmashtirilganZapchastRoyxati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='almashtirilganZapchastRoyxati')),
                ('texnik_korik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.texnikkorik')),
            ],
            options={
                'verbose_name': 'AlmashtirilganZapchastRoyxati',
                'verbose_name_plural': 'AlmashtirilganZapchastRoyxati',
            },
        ),
    ]
